forcedotcom/SalesforceMobileSDK-Windows

- SalesforceSDK/Salesforce.SDK.Phone/Source/App/ContinuationManagerImpl.cs
- SalesforceSDK/Salesforce.SDK.Phone/Source/App/SFApplicationHelper.cs
- SalesforceSDK/Salesforce.SDK.Store/Source/App/SFApplicationHelper.cs
The OnActivated page helper was missing code to set the root frame, which was messing up my sample app from properly activating via protocol activation.  Cleaned up the code a bit as well during the bug fix.
@smcnulty-sfdc
> Fix OnActivated page helper

- SalesforceSDK/Salesforce.SDK.SmartSync/Manager/SyncManager.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SyncState.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Util/Constants.cs
- SalesforceSDK/Salesforce.Sample.SmartSyncExplorer/Salesforce.Sample.SmartSyncExplorer.Shared/ViewModel/ContactObject.cs
- SalesforceSDK/Salesforce.Sample.SmartSyncExplorer/Salesforce.Sample.SmartSyncExplorer.Shared/ViewModel/ContactSyncViewModel.cs
Changelist adds ability to resync only new data, skipping unchanged items from server side.
> Resync only new data

- SalesforceSDK/Salesforce.SDK.Core/Source/Auth/AccountManager.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Manager/SyncManager.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SyncState.cs
- SalesforceSDK/Salesforce.SDK.Store.Test/Salesforce.SDK.Store.Test.csproj
- SalesforceSDK/Salesforce.SDK.Store.Test/Source/SmartStore/SmartSyncTests.cs
- SalesforceSDK/Salesforce.SDK.Store.Test/Source/SmartStore/TestCredentials.cs
Unit tests for SmartSync covering sync down, sync up, resync.
> Unit tests for SmartSync.

- SalesforceSDK/Salesforce.SDK.SmartSync/Manager/SyncManager.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/MruSyncTarget.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SoqlSyncTarget.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SoslSyncTarget.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SyncTarget.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Salesforce.SDK.SmartSync.csproj
- SalesforceSDK/Salesforce.SDK.Store.Test/Source/SmartStore/SmartSyncTests.cs
- SalesforceSDK/Salesforce.Sample.SmartSyncExplorer/Salesforce.Sample.SmartSyncExplorer.Shared/ViewModel/ContactSyncViewModel.cs
- SalesforceSDK/Salesforce.Sample.SmartSyncExplorer/Salesforce.Sample.SmartSyncExplorer.Windows/Salesforce.Sample.SmartSyncExplorer.Windows.csproj
SyncTarget is now split into multiple classes and can accept targets made by SDK users.
> Refactor of SyncTarget

- SalesforceSDK/Salesforce.SDK.Core/Source/App/SalesforceApplication.cs
@smcnulty-sfdc would you please review these changes and merge if everything looks good. Particularly please give feedback if you think method names should be different or if you think there is a better way of doing this. Thx
> Enable MobileSdk to use an external logging provider

- SalesforceSDK/Salesforce.SDK.Core/Source/App/SalesforceApplication.cs
> add using statement for logging

- SalesforceSDK/Salesforce.SDK.Core/Source/Auth/AccountManager.cs
- SalesforceSDK/Salesforce.SDK.Core/Source/Auth/AuthStorageHelper.cs
> Minor fixes to SDK logging

- SalesforceSDK/Salesforce.SDK.SmartStore/Salesforce.SDK.SmartStore.csproj
- SalesforceSDK/Salesforce.SDK.SmartStore/Source/Store/ISmartStore.cs
- SalesforceSDK/Salesforce.SDK.SmartStore/Source/Store/SmartStore.cs
> Extract SmartStore interface

- SalesforceSDK/PullNugetFiles.bat
- SalesforceSDK/Salesforce.SDK.App/Auth/PincodeOptions.cs
- SalesforceSDK/Salesforce.SDK.App/Salesforce.SDK.App.csproj
- SalesforceSDK/Salesforce.SDK.Core.NuGet/Package.nuspec
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.Shared/App.xaml.cs
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.Shared/Pages/MainPage.xaml.cs
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.Shared/settings/Config.cs
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.Windows/Salesforce.Universal.Template.Windows.csproj
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.Windows/packages.config
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.WindowsPhone/Salesforce.Universal.Template.WindowsPhone.csproj
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.WindowsPhone/packages.config
Updates for the template and NuGet generation.
> Template & NuGet updates for Salesforce.SDK.App

- SalesforceSDK/NoteSync/NoteSync.Shared/ViewModel/NoteSyncViewModel.cs
- SalesforceSDK/Salesforce.SDK.SmartStore/Source/Store/DBHelper.cs
- SalesforceSDK/Salesforce.SDK.SmartStore/Source/Store/DBOpenHelper.cs
- SalesforceSDK/Salesforce.SDK.SmartStore/Source/Store/SmartStore.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Manager/CacheManager.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Manager/SyncManager.cs
- SalesforceSDK/Salesforce.SDK.Store.Test/Source/SmartStore/SmartStoreTest.cs
- SalesforceSDK/Salesforce.SDK.Store.Test/Source/SmartStore/SmartStoreTestLoadTest.cs
- SalesforceSDK/Salesforce.SDK.Store.Test/Source/SmartStore/SmartSyncTests.cs
- SalesforceSDK/Salesforce.Sample.NativeSmartStoreSample/Salesforce.Sample.NativeSmartStoreSample.Shared/utilities/SmartStoreExtension.cs
- SalesforceSDK/Salesforce.Sample.SmartSyncExplorer/Salesforce.Sample.SmartSyncExplorer.Shared/ViewModel/ContactSyncViewModel.cs
SDK users can now make use of a global SmartStore instance and specify which SmartStore instance to target for commands.
> Global SmartStore.

- SalesforceSDK/Salesforce.SDK.Phone/Source/Pages/AccountPage.xaml.cs
- SalesforceSDK/Salesforce.SDK.Store/Source/Pages/AccountPage.xaml.cs
ContinueWebAuthentication should dispatch to the ui thread when attempting to show a flyout
> Fix a cross thread bug when showing a flyout

- SalesforceSDK/Salesforce.SDK.App/App/SalesforceApplication.cs
> call app lifecycle base methods when overriding

- SalesforceSDK/NoteSync/NoteSync.Shared/Data/ContentSoqlSyncDownTarget.cs
- SalesforceSDK/NoteSync/NoteSync.Shared/ViewModel/NoteSyncViewModel.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Manager/SyncManager.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/MruSyncDownTarget.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SoqlSyncDownTarget.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SoslSyncDownTarget.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SyncDownTarget.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SyncTarget.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SyncUpTarget.cs
- SalesforceSDK/Salesforce.SDK.Store.Test/Source/SmartStore/SmartSyncTests.cs
- SalesforceSDK/Salesforce.Sample.SmartSyncExplorer/Salesforce.Sample.SmartSyncExplorer.Shared/ViewModel/ContactSyncViewModel.cs
> Allow Override for Id and ModfiedDate Fields

- SalesforceSDK/Salesforce.SDK.Core/Source/Rest/ClientManager.cs
- SalesforceSDK/Salesforce.SDK.Core/Source/Rest/RestClient.cs
- SalesforceSDK/Salesforce.SDK.Store.Test/Source/Rest/RestClientTest.cs
- SalesforceSDK/Salesforce.SDK.Store.Test/Source/TestCredentials.cs
> Support for unauthenticated client

- SalesforceSDK/PullNugetFiles.bat
- SalesforceSDK/Salesforce.SDK.Core.NuGet/Package.nuspec
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.Windows/Salesforce.Universal.Template.Windows.csproj
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.Windows/packages.config
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.WindowsPhone/Salesforce.Universal.Template.WindowsPhone.csproj
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.WindowsPhone/packages.config
- SalesforceSDK/SalesforceSDK.sln
> Changes for 3.2.0 release

- SalesforceSDK/Salesforce.SDK.App/App/SalesforceApplication.cs
- SalesforceSDK/Salesforce.SDK.Core/Source/Auth/OAuth2.cs
- SalesforceSDK/Salesforce.SDK.Store.Test/Source/SmartStore/SmartSyncTests.cs
- SalesforceSDK/Salesforce.Sample.Salesforce1.Container/Salesforce.Sample.Salesforce1.Container.Shared/pages/MainPage.xaml.cs
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.Shared/Pages/MainPage.xaml
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.Shared/Pages/MainPage.xaml.cs
> Add Contacts Sample to Template App

- SalesforceSDK/Salesforce.SDK.Core.NuGet/Package.nuspec
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.Windows/Salesforce.Universal.Template.Windows.csproj
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.Windows/packages.config
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.WindowsPhone/Salesforce.Universal.Template.WindowsPhone.csproj
- SalesforceSDK/Salesforce.Universal.Template/Salesforce.Universal.Template.WindowsPhone/packages.config
> Bump Up Version to 3.3.0-unstable

- SalesforceSDK/Salesforce.SDK.Core/Source/Adaptation/PlatformAdapter.cs
- SalesforceSDK/Salesforce.SDK.Universal/Properties/AssemblyInfo.cs
- SalesforceSDK/Salesforce.SDK.Universal/Salesforce.SDK.Universal.csproj
- SalesforceSDK/Salesforce.SDK.Universal/Source/App/SFApplicationHelper.cs
- SalesforceSDK/Salesforce.SDK.Universal/Source/Auth/AuthHelper.cs
- SalesforceSDK/Salesforce.SDK.Universal/Source/Pages/AccountPage.xaml
- SalesforceSDK/Salesforce.SDK.Universal/Source/Pages/AccountPage.xaml.cs
This cannot be checked into the current solution as it would break dev for 2013. You can add Salesforce.SDK.Universal to a Windows 10 project.
> Adding universal project to unstable SDK.

- SalesforceSDK/Salesforce.SDK.App/Hybrid/HybridMainPage.cs
- SalesforceSDK/Salesforce.SDK.Core/Salesforce.SDK.Core.csproj
- SalesforceSDK/Salesforce.SDK.Core/Source/Net/HttpCall.cs
- SalesforceSDK/Salesforce.SDK.SmartStore/Source/Store/DBHelper.cs
- SalesforceSDK/Salesforce.SDK.SmartStore/Source/Store/SmartStore.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Manager/SyncManager.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SoqlSyncDownTarget.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SoslSyncDownTarget.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SyncDownTarget.cs
- SalesforceSDK/Salesforce.SDK.SmartSync/Model/SyncUpTarget.cs
- SalesforceSDK/Salesforce.SDK.Universal/Properties/AssemblyInfo.cs
- SalesforceSDK/Salesforce.SDK.Universal/Source/Pages/AccountPage.xaml.cs
@kchitalia @smcnulty-sfdc @wpeter-sfdc @jbernoudy @jhorstsf
> Fix a number of build warnings

- SalesforceSDK/CordovaPluginJavascript/com.salesforce.plugin.smartstoreProxy.js
- SalesforceSDK/NoteSync/NoteSync.Windows/NoteSync.Windows.csproj
- SalesforceSDK/NoteSync/NoteSync.WindowsPhone/NoteSync.WindowsPhone.csproj
> Fix build errors for sample app

- SalesforceSDK/Salesforce.SDK.Hybrid.SmartStore/Salesforce.SDK.Hybrid.SmartStore.csproj
- SalesforceSDK/Salesforce.SDK.Hybrid.SmartStore/Source/Store/SmartStore.cs
- SalesforceSDK/Salesforce.SDK.Hybrid.SmartStore/Source/Store/StoreCursor.cs
@kchitalia @smcnulty-sfdc @wpeter-sfdc
> Add support for StoreCursor to Hybrid SDK

- SalesforceSDK/Salesforce.SDK.Hybrid.SmartStore/Source/Store/ISmartStore.cs
> expose smartstore methods through it's interface

- SalesforceSDK/Hybrid/Rest/ApiVersionStrings.cs
I forgot to clean my git repro after moving the files so this one was there, but not checked in as it got deleted by accident during the merge.
> Replacing file lost in merge.

- SalesforceSDK/Core/Auth/AuthStorageHelper.cs
- SalesforceSDK/Hybrid/Auth/HybridAccountManager.cs
Cache the current account in AccountManager, fix encryption init issues for hybrid.core.
> Fix for some account related issues

- SalesforceSDK/Hybrid.SmartStore/Store/ISmartStore.cs
- SalesforceSDK/Hybrid.SmartStore/Store/SmartStore.cs
- SalesforceSDK/Hybrid.SmartStore/Store/StoreCursor.cs
1) Fix issue of hybrid.smartstore using a bad instance of the native
smartstore
2) removed extra calls to createmetatable & serialization
3) All "smartstore" hybrid methods return json string instead of object
> FIxing up hybrid.smartstore

- SalesforceSDK/App/App.csproj
- SalesforceSDK/Core/Core.csproj
- SalesforceSDK/Hybrid.SmartStore/Hybrid.SmartStore.csproj
- SalesforceSDK/Hybrid.SmartSync/Hybrid.SmartSync.csproj
- SalesforceSDK/Hybrid/Hybrid.Core.csproj
- SalesforceSDK/Phone/Phone.csproj
- SalesforceSDK/SmartStore/SmartStore.csproj
- SalesforceSDK/SmartSync/SmartSync.csproj
- SalesforceSDK/Store/Store.csproj
Small fix to allow for better submoduling of SDK.
> Pointing nuget restore in csproj to refer to solution location

- SalesforceSDK/Core/Auth/SDKManager.cs
- SalesforceSDK/Core/Core.csproj
- SalesforceSDK/Universal/Source/Pages/AccountPage.xaml.cs
> make sure servers.xml gets copied to output

- SalesforceSDK/Core/Auth/SDKManager.cs
- SalesforceSDK/Core/Core.csproj
- SalesforceSDK/Core/Settings/ConfigHelper.cs
- SalesforceSDK/Core/Settings/SalesforceConfig.cs
- SalesforceSDK/Phone/Pages/AccountPage.xaml.cs
- SalesforceSDK/Store/Pages/AccountPage.xaml.cs
- SalesforceSDK/Universal/Source/Hybrid/BootConfig.cs
- SalesforceSDK/Universal/Source/Pages/AccountPage.xaml.cs
> SDKManager to properly await initialization

- SalesforceSDK/Universal/Universal.csproj
> use SolutionDir instead of relative path in csproj

- SalesforceSDK/Core/Core.csproj
Servers.xml wasn't being picked up properly after the port.
> Fixing servers.xml

- SalesforceSDK/Core/Net/HttpCall.cs
needed to set a result in the task, else we get stuck on await task.Task.
@kchitalia
> Updating HttpCall to allow setting the UserAgentHeader on a background thread

- SalesforceSDK/Core/Core.csproj
- SalesforceSDK/Hybrid.SmartStore/Hybrid.SmartStore.csproj
- SalesforceSDK/Hybrid.SmartSync/Hybrid.SmartSync.csproj
- SalesforceSDK/Hybrid/Hybrid.csproj
- SalesforceSDK/SmartStore/SmartStore.csproj
- SalesforceSDK/SmartSync/SmartSync.csproj
- SalesforceSDK/Universal/Universal.csproj
Adding the projectname tag as according to Microsoft we this need for a Cordova project to successfully add the plugin.
> Add projectname to .csproj files

- SalesforceSDK/Core/Auth/AccountManager.cs
- SalesforceSDK/Core/Auth/OAuth2.cs
- SalesforceSDK/Core/Core.csproj
- SalesforceSDK/Core/Logging/ILoggingService.cs
- SalesforceSDK/Core/Logging/LoggingLevel.cs
- SalesforceSDK/Core/Net/HttpCall.cs
- SalesforceSDK/Core/Rest/ClientManager.cs
- SalesforceSDK/Hybrid/Auth/HybridAccountManager.cs
- SalesforceSDK/Hybrid/Logging/Logger.cs
- SalesforceSDK/Salesforce.SDK.Tests/Salesforce.SDK.Tests.csproj
- SalesforceSDK/Salesforce.SDK.Tests/project.json
- SalesforceSDK/SmartStore/SmartStore.csproj
- SalesforceSDK/SmartSync/SmartSync.csproj
- SalesforceSDK/Universal/App/SalesforceApplication.cs
- SalesforceSDK/Universal/Auth/AuthHelper.cs
- SalesforceSDK/Universal/Auth/AuthStorageHelper.cs
- SalesforceSDK/Universal/Auth/PincodeDialog.xaml.cs
- SalesforceSDK/Universal/Auth/PincodeManager.cs
- SalesforceSDK/Universal/Hybrid/HybridMainPage.cs
- SalesforceSDK/Universal/Native/NativeMainPage.cs
- SalesforceSDK/Universal/Pages/AccountPage.xaml.cs
> Updating logger to include method, class and line number.

- .gitignore
- SalesforceSDK/Core/Auth/AccountManager.cs
- SalesforceSDK/Core/Auth/OAuth2.cs
- SalesforceSDK/Core/Core.csproj
- SalesforceSDK/Core/Rest/ClientManager.cs
- SalesforceSDK/Core/Rest/IRestClient.cs
- SalesforceSDK/Core/Rest/IRestResponse.cs
- SalesforceSDK/Core/Rest/RestClient.cs
- SalesforceSDK/Core/Rest/RestResponse.cs
- SalesforceSDK/Hybrid/Rest/RestClient.cs
- SalesforceSDK/Hybrid/Rest/RestResponse.cs
- SalesforceSDK/Salesforce.SDK.Tests/Salesforce.SDK.Tests.csproj
- SalesforceSDK/Salesforce.SDK.Tests/Salesforce.SDK.Tests.nuget.props
- SalesforceSDK/Salesforce.SDK.Tests/Salesforce.SDK.Tests.nuget.targets
- SalesforceSDK/Salesforce.SDK.Tests/Source/Rest/RestClientTest.cs
- SalesforceSDK/Salesforce.SDK.Tests/Source/SmartStore/SmartSyncTests.cs
- SalesforceSDK/Salesforce.SDK.Tests/packages.config
- SalesforceSDK/Salesforce.SDK.Tests/project.json
- SalesforceSDK/SmartSync/Manager/SyncManager.cs
- SalesforceSDK/SmartSync/Model/SoqlSyncDownTarget.cs
- SalesforceSDK/Universal/Hybrid/HybridMainPage.cs
So we can write proper unit tests for any services that consume these classes
> put RestClient and RestResponse behind interfaces

- SalesforceSDK/Core/Auth/AccountManager.cs
- SalesforceSDK/Core/Auth/AuthenticatedAccountChangedEventArgs.cs
- SalesforceSDK/Core/Core.csproj
- SalesforceSDK/Universal/Auth/AuthStorageHelper.cs
> add event to notify when account is logged in or out

- SalesforceSDK/Core/Auth/AccountManager.cs
- SalesforceSDK/Core/Auth/AuthenticatedAccountChangedEventArgs.cs
- SalesforceSDK/Universal/Auth/AuthStorageHelper.cs
> raise account changed event property on logout as well

- SalesforceSDK/Core/Rest/ApiVersionStrings.cs
> bumping api version string

- SalesforceSDK/Core/Auth/AccountManager.cs
- SalesforceSDK/Universal/Auth/AuthStorageHelper.cs
> fix bug where logging out and login again would not raise account changed event

- SalesforceSDK/Core/Net/HttpCall.cs
- SalesforceSDK/Core/Settings/IApplicationInformationService.cs
- SalesforceSDK/Hybrid/Auth/HybridAccountManager.cs
- SalesforceSDK/Universal/App/ApplicationService.cs
- SalesforceSDK/Universal/Hybrid/HybridMainPage.cs
This is what the user agent will look like:
SalesforceMobileSDK/4.0.0 (Windows.Desktop/10.0.10240.16384 Salesforce Sample Container 1.0.0) native 
For Hybrid apps, "native" will be replaced by "hybrid"
> Fix user agent to match Android and iOS

- SalesforceSDK/TemplateWizard/TemplateForm.xaml
- SalesforceSDK/TemplateWizard/TemplateWizard.csproj
- SalesforceSDK/TemplateWizard/packages.config
Just had to update to the latest version of the libraries for VS 2015
> Fix errors in Template App Wizard

- SalesforceSDK/Core/Rest/ApiVersionStrings.cs
- SalesforceSDK/Universal/Hybrid/HybridMainPage.cs
@kchitalia @wpeter-sfdc @smcnulty-sfdc
> add ability to override API version

- SalesforceSDK/Core/Net/HttpCall.cs
- SalesforceSDK/Core/Rest/IRestResponse.cs
- SalesforceSDK/Core/Rest/RestClient.cs
- SalesforceSDK/Core/Rest/RestResponse.cs
@kchitalia @smcnulty-sfdc @wpeter-sfdc
> add ErrorReason and Response headers to rest response

- SalesforceSDK/Core/Net/HttpCall.cs
- SalesforceSDK/Core/Rest/IRestClient.cs
- SalesforceSDK/Core/Rest/RestClient.cs
> add support for network call cancellation

- SalesforceSDK/Core/Auth/AccountManager.cs
- SalesforceSDK/Core/Auth/OAuth2.cs
- SalesforceSDK/Core/Net/HttpCall.cs
- SalesforceSDK/Core/Rest/ClientManager.cs
- SalesforceSDK/Core/Rest/RestClient.cs
- SalesforceSDK/Hybrid/Auth/HybridAccountManager.cs
- SalesforceSDK/Hybrid/Rest/ClientManager.cs
- SalesforceSDK/Salesforce.SDK.Tests/Source/Rest/RestClientTest.cs
- SalesforceSDK/Salesforce.SDK.Tests/Source/SmartStore/SmartSyncTests.cs
- SalesforceSDK/Salesforce.SDK.Tests/Tests.csproj
- SalesforceSDK/Salesforce.SDK.Tests/project.json
- SalesforceSDK/Universal/App/SalesforceApplication.cs
- SalesforceSDK/Universal/Auth/PincodeDialog.xaml.cs
- SalesforceSDK/Universal/Hybrid/HybridMainPage.cs
- SalesforceSDK/Universal/Native/NativeMainPage.cs
- SalesforceSDK/Universal/Pages/AccountPage.xaml.cs
and update UT project to use latest version of sqlite.uap and fix nuget references to use UWP nuget packages
> add cancellation support to more async methods

- SalesforceSDK/Core/Auth/IAuthHelper.cs
- SalesforceSDK/Core/Auth/OAuth2.cs
- SalesforceSDK/Core/Net/HttpCall.cs
- SalesforceSDK/Core/Rest/IRestResponse.cs
- SalesforceSDK/Core/Rest/RestRequest.cs
- SalesforceSDK/Universal/App/SalesforceApplication.cs
- SalesforceSDK/Universal/Auth/AuthHelper.cs
- SalesforceSDK/Universal/Auth/AuthStorageHelper.cs
- SalesforceSDK/Universal/Hybrid/BootConfig.cs
- SalesforceSDK/Universal/Hybrid/HybridMainPage.cs
- SalesforceSDK/Universal/Security/HmacSHA256KeyGenerator.cs
- SalesforceSDK/Universal/Strings/en-US/resources.resw
- SalesforceSDK/Universal/Universal.csproj
> Fix a few misspellings and build warnings

- SalesforceSDK/CordovaPluginJavascript/com.salesforce.plugin.oauthProxy.js
- SalesforceSDK/CordovaPluginJavascript/com.salesforce.plugin.smartstoreProxy.js
- SalesforceSDK/Core.NuGet/Package.nuspec
- SalesforceSDK/Core.NuGet/tools/install.ps1
- SalesforceSDK/Core/Properties/AssemblyInfo.cs
- SalesforceSDK/Core/Strings/en/resources.resw
- SalesforceSDK/Hybrid.SmartStore/Properties/AssemblyInfo.cs
- SalesforceSDK/Hybrid.SmartSync/Properties/AssemblyInfo.cs
- SalesforceSDK/SmartStore/Properties/AssemblyInfo.cs
- SalesforceSDK/SmartSync/Properties/AssemblyInfo.cs
- SalesforceSDK/Universal/App/ApplicationService.cs
- SalesforceSDK/Universal/Strings/en/resources.resw
Reverts forcedotcom/SalesforceMobileSDK-Windows#190
> Revert "Unstable"

- SalesforceSDK/Core/Settings/SalesforceConfig.cs
previous code was trying to decrypt json that was not encrypted, causing it to fail every time
> fix config retrieval always failing

- SalesforceSDK/Core/Logging/ILoggingService.cs
- SalesforceSDK/Hybrid/Logging/Logger.cs
> add optional log message when logging exceptions

- SalesforceSDK/SmartStore/Store/ISmartStore.cs
- SalesforceSDK/SmartStore/Store/SmartStore.cs
> Delete user specific store on logout

- SalesforceSDK/Salesforce.SDK.Tests/Tests.csproj
Updating the SQLite.UWP reference.
> Update SQLite.UWP to latest version in UT project

- SalesforceSDK/Salesforce.SDK.Tests/Tests.csproj
- SalesforceSDK/Universal/Pages/AccountPage.xaml
- SalesforceSDK/Universal/Pages/AccountPage.xaml.cs
@jbernoudy This should fix the UI issue for the Choose Server and Add Connection screens
> Fix UI layout issue for Chose Server and Add Connection screen

- SalesforceSDK/template/createapp.ps1
1. support to check sdk version 
2. create all application files inside a folder using the application name under the users target location 
3.If the same application folder is existing there, the create will replace the old one 
4. validate the input at each creation step instead of at the end to allow the user to correct the stuff earlier, instead of redo the whole process
> Script improve work

- SalesforceSDK/Analytics/Analytics.csproj
- SalesforceSDK/Analytics/Model/DeviceAppAttributes.cs
- SalesforceSDK/Analytics/Model/InstrumentationEvent.cs
- SalesforceSDK/Analytics/Properties/AssemblyInfo.cs
- SalesforceSDK/Analytics/Store/EventStoreManager.cs
- SalesforceSDK/Analytics/Store/IEventStoreManager.cs
- SalesforceSDK/Analytics/packages.config
- SalesforceSDK/SalesforceSDK.sln
@bhariharan @wpeter-sfdc @maliroteh
> First commit for AILTN

- SalesforceSDK/template/createapp.ps1
https://github.com/forcedotcom/SalesforceMobileSDK-Windows/issues/216
> solve usage issue
